[package]
name = "day05a"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9"
num = "0.1"
regex = "0.1"
nom = "7.0"